# Generated by Django 4.2.9 on 2024-01-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommender", "0002_food_imagepath"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
